rm(list=ls())
survey <- read.csv("D:/dataanalytics/project/survey.csv")
View(survey)
nrow(survey) 
ncol(survey)
colnames(survey)
summary(survey)
library(dplyr)
survey <- survey %>% mutate(Chicken.Masala = replace(Chicken.Masala, Chicken.Masala =="",NA)) %>% mutate(Mutton.Masala = replace(Mutton.Masala,Mutton.Masala=="",NA))
is.na(survey)
sum(is.na(survey))
sum(is.na(survey$`Chicken.Masala`))
sum(is.na(survey$`Mutton.Masala`))
library(mice)
md.pattern(survey)
survey_imp<-select(survey,c("Chilli.Powder","Turmeric.Powder","Sambar.Powder","Rasam.Powder","Chicken.Masala","Mutton.Masala"))
View(survey_imp)
library(VIM)
library(Rcpp)
survey_imp$Chilli.Powder = substr(survey_imp$Chilli.Powder,1,nchar(survey_imp$Chilli.Powder)-1)
survey_imp$Turmeric.Powder = substr(survey_imp$Turmeric.Powder,1,nchar(survey_imp$Turmeric.Powder)-1)
survey_imp$Sambar.Powder = substr(survey_imp$Sambar.Powder,1,nchar(survey_imp$Sambar.Powder)-1)
survey_imp$Rasam.Powder = substr(survey_imp$Rasam.Powder,1,nchar(survey_imp$Rasam.Powder)-1)
survey_imp$Chicken.Masala = substr(survey_imp$Chicken.Masala,1,nchar(survey_imp$Chicken.Masala)-1)
survey_imp$Mutton.Masala = substr(survey_imp$Mutton.Masala,1,nchar(survey_imp$Mutton.Masala)-1)
survey_imp$Chilli.Powder = as.numeric(survey_imp$Chilli.Powder)
survey_imp$Turmeric.Powder = as.numeric(survey_imp$Turmeric.Powder)
survey_imp$Sambar.Powder = as.numeric(survey_imp$Sambar.Powder)
survey_imp$Rasam.Powder = as.numeric(survey_imp$Rasam.Powder)
survey_imp$Chicken.Masala = as.numeric(survey_imp$Chicken.Masala)
survey_imp$Mutton.Masala = as.numeric(survey_imp$Mutton.Masala)
mice_imputed <- mice(survey_imp,m=4, maxit=25)
mice_imputed$method
imputed_data <- complete(mice_imputed,4)
View(imputed_data)
d1 <- select(survey,c("Name","Gender","Age","Size.of.Family","Are.you.a.regular.user.of.Spices.","How.often.do.you.purchase.Spices.Powder"))
d2 <- select(survey,c("Price","Packaging","Taste","Freshness","Quality","Brand.Awareness","Advertisement","Discounts.Offers","User.Recommendation","Shopkeeper.Recommendation"))
dy <- cbind(d1,imputed_data)
data <- cbind(dy,d2)
View(data)
summary(data)
str(data)
library(SmartEDA)
ExpData(data)
ExpCTable(data)
ExpCatViz(data)
pvalues1 = c()
for (i in 13:22){
  pv = ExpStat(data$Gender,data[,i],valueOfGood = 1)
  pvalues1 = append(pvalues1,pv[3])
}
pvalues1 = as.numeric(pvalues1)
barplot(pvalues1,names.arg = c("Price","Packaging","Taste","Freshness","Quality","Brand.Awareness","Ads","Disc.Offers","User.Recomm","Shopkeeper.Recomm"))
abline(h=0.05,col='red')
pvalues2=c()
for (i in 13:22){
  pv = ExpStat(data$Age,data[,i],valueOfGood = 1)
  pvalues2 = append(pvalues2,pv[3])
}
pvalues2 = as.numeric(pvalues2)
barplot(pvalues2,names.arg = c("Price","Packaging","Taste","Freshness","Quality","Brand.Awareness","Ads","Disc.Offers","User.Recomm","Shopkeeper.Recomm"))
abline(h=0.05,col='red')
pvalues3=c()
for (i in 13:22){
  pv = ExpStat(data$Size.of.Family,data[,i],valueOfGood = 1)
  pvalues3 = append(pvalues3,pv[3])
}
pvalues3 = as.numeric(pvalues3)
barplot(pvalues3,names.arg = c("Price","Packaging","Taste","Freshness","Quality","Brand.Awareness","Ads","Disc.Offers","User.Recomm","Shopkeeper.Recomm"))
abline(h=0.05,col='red')
pvalues4 = c()
for (i in 13:22){
  pv = ExpStat(data$How.often.do.you.purchase.Spices.Powder,data[,i],valueOfGood = 1)
  pvalues4 = append(pvalues4,pv[3])
}
pvalues4 = as.numeric(pvalues4)
barplot(pvalues4,names.arg = c("Price","Packaging","Taste","Freshness","Quality","Brand.Awareness","Ads","Disc.Offers","User.Recomm","Shopkeeper.Recomm"))
abline(h=0.05,col='red')
pvalues5 = c()
for (i in 7:12){
  pv = ExpStat(data$How.often.do.you.purchase.Spices.Powder,data[,i],valueOfGood = 1)
  pvalues5 = append(pvalues5,pv[3])
}
pvalues5 = as.numeric(pvalues5)
barplot(pvalues5,names.arg = c("chilli powder","turmeric powder","sambhar powder","rasam powder","chicken masala","mutton masala"))
abline(h=0.05,col='red')

